@url=http://localhost:8181/api/cards

POST {{url}}/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc1ZWM4NjI3NzdjYjYzMTcxNWY3N2IiLCJpc0FkbWluIjpmYWxzZSwiaXNCdXNpbmVzcyI6dHJ1ZSwiaWF0IjoxNjg2NTY2OTEzLCJleHAiOjE2ODkxNTg5MTN9.nImxOnBYzbh1Lte_jsqwJMz-2QOhXsPsMfOdMVtihrs
Content-Type: application/json

{
  "title": "nnn",
  "subTitle": "test",
  "description": "save the card pls",
  "phone": "0500000000",
  "email": "joi@gmail.com",
  "image": {
    "url": "https://cdn.pixabay.com/photo/2020/04/07/17/01/chicks-5014152_960_720.jpg",
    "alt": "yellow fluffy chickens"
  },
  "address": {
    "state": "",
    "country": "Israel",
    "city": "Ashkeluna",
    "street": "jump street",
    "houseNumber": 23,
    "zip": 0
  },
  "bizNumber": 3680978
}